info/urls.py
from django.contrib import admin
from django.urls import path

from info import views
from info.views import InfoList
from info.views import ReplyList
import info.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', InfoList.as_view(), name='i_list'),
    path('infodetail/<movie_id>/', info.views.infodetail, name='i_detail'),
    path('replylist/<int:movie_id_id>', ReplyList.as_view(), name='r_list'),
    path('replycreate/<movie_id>/', info.views.replycreate, name='r_create'),
    path('replycreate2/<movie_id>/', info.views.replydbcreate, name='r_dbcreate'),
    path('replydelete/', info.views.replydelete, name='r_delete'),
    path('replyupdate/<reply_id>/<movie_id>/<content>/', info.views.replyupdate, name='r_update'),
    path('replyupdate2/<movie_id>/', info.views.replydbupdate, name='r_dbupdate'),
]

# from django.conf.urls.static import static
# from django.conf import settings
#
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movie/urls.py
from django.contrib import admin
from django.urls import path, include

import info.urls
import reserve.urls
import reserve.views
import member.urls
from info.views import InfoList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reserve/', include(reserve.urls)),
    path('member/',include(member.urls)),
    path('',include(info.urls)),
]

reserve/urls.py
from django.contrib import admin
from django.urls import path
from reserve.views import *

app_name = 'reserve'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book', Reservation_main.as_view(), name='book'),
    path('time/<int:movie_id>', select_time, name='time'),
    path('seat/<watchday>&<int:watchtime>&<int:theater>', select_seat, name='seat'),
    path('save', reserve_save, name='save'),
    path('fin/<insert_id>', reserve_fin, name='fin'),
    path('hadoop', hot, name='hot'),
]

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>

    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Quicksand:400,700|Questrial"
          rel="stylesheet"/>
    <link href="{% static 'default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#logout").click(function () {
                $.ajax({
                    url: "{% url 'member_logout' %}",
                    success: function () {
                        alert("로그아웃!")
                        location.href = "{% url 'i_list' %}"  //이거말고 메인으로
                    }
                })
            }) // 로그아웃

            $("#reserve").click(function () {
                id = '{{ request.session.id }}'
                if (id == "") {
                    alert('로그인이 필요한 서비스입니다.')
                    location.href = "{% url 'login' %}"
                } else {
                    location.href = "{% url 'reserve:book' %}"
                }
            })
            $("#member_info").click(function () {
                id = '{{ request.session.id }}'
                if (id == "") {
                    alert('로그인이 필요한 서비스입니다.')
                    location.href = "{% url 'login' %}"
                } else {
                    location.href = "{% url 'login_info' %}"
                }
            })
        })
    </script>
    {% block script %}{% endblock %}
    {% block style %}{% endblock %}
</head>
<body>
<div id="header-wrapper">
    <br>
    {% if request.session.id == "" %}
        <div style="text-align: right;margin-right: 20px">
            <a href="{% url 'login' %}" style="color: white;"><b>로그인</b></a><font style="color: dimgray">|</font>&nbsp&nbsp&nbsp<a
                href="{% url 'create' %}" style="color: white"><b>회원가입</b></a>
        </div>
    {% else %}
        <div style="text-align: right;margin-right: 60px">
        <font style="color: white">{{ request.session.id }}님 환영합니다.&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp</font>
            <a id="logout" style="color: white;"><b>로그아웃</b></a>
        </div>
    {% endif %}

    <div id="header" class="container">
        <div>
            <h1><a style="color: white; text-decoration: none;" href="{% url 'i_list' %}">Big MegaBox</a></h1>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'i_list' %}">&nbsp&nbsp&nbsp영 화&nbsp&nbsp&nbsp</a></li>
                <li><a id="reserve" href="#">&nbsp&nbsp&nbsp예 매&nbsp&nbsp&nbsp</a></li>
                <li><a id="member_info" href="#">회원 정보</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="wrapper">
    <div id="welcome" class="container">
        {% block content %}{% endblock %}
    </div>
</div>
<div id="footer">
    <div class="container">
        <div class="fbox1">
            <span class="icon icon-map-marker"></span>
            <span>THEJOEUN ACADEMY Corp.
			<br/>Sinchon Campus, 708</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-phone"></span>
            <span>
				Telephone: +1 800 123 4657
			</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-envelope"></span>
            <span>businessname@business.com</span>
        </div>
    </div>
</div>
<div id="copyright">
    <p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by <a
            href="http://templated.co" rel="nofollow">TEMPLATED</a>.<br>
        4조(박현정, 양준호, 유승종) - django project.</p>
</div>

</body>
</html>

templates/base1.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>

    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Quicksand:400,700|Questrial"
          rel="stylesheet"/>
    <link href="{% static 'default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#logout").click(function () {
                $.ajax({
                    url: "{% url 'member_logout' %}",
                    success: function () {
                        alert("로그아웃!")
                        location.href = "{% url 'i_list' %}"  //이거말고 메인으로
                    }
                })
            }) // 로그아웃

            $("#reserve").click(function () {
                id = '{{ request.session.id }}'
                if (id == "") {
                    alert('로그인이 필요한 서비스입니다.')
                    location.href = "{% url 'login' %}"
                } else {
                    location.href = "{% url 'reserve:book' %}"
                }
            })
            $("#member_info").click(function () {
                id = '{{ request.session.id }}'
                if (id == "") {
                    alert('로그인이 필요한 서비스입니다.')
                    location.href = "{% url 'login' %}"
                } else {
                    location.href = "{% url 'login_info' %}"
                }
            })
        })
    </script>
    {% block script %}{% endblock %}
    {% block style %}{% endblock %}
</head>
<body>
<div id="header-wrapper">
    <br>
    {% if request.session.id == "" %}
        <div style="text-align: right;margin-right: 20px">
            <a href="{% url 'login' %}" style="color: white;"><b>로그인</b></a>&nbsp&nbsp&nbsp<font style="color: dimgray">|</font>&nbsp&nbsp&nbsp<a
                href="{% url 'create' %}" style="color: white"><b>회원가입</b></a>
        </div>
    {% else %}
        <div style="text-align: right;margin-right: 60px">
        <font style="color: white">{{ request.session.id }}님 환영합니다.&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp</font>
            <a href="#" id="logout" style="color: white;"><b>로그아웃</b></a>
        </div>
    {% endif %}

    <div id="header" class="container">
        <div>
            <h1><a style="color: white; text-decoration: none;" href="{% url 'i_list' %}">Big MegaBox</a></h1>
        </div>
        <div id="menu">
            <ul>
                <li class="active"><a href="{% url 'i_list' %}">&nbsp&nbsp&nbsp영 화&nbsp&nbsp&nbsp</a></li>
                <li><a id="reserve" href="#">&nbsp&nbsp&nbsp예 매&nbsp&nbsp&nbsp</a></li>
                <li><a id="member_info" href="#">회원 정보</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="wrapper">
    <div id="welcome" class="container">
        {% block content %}{% endblock %}
    </div>
</div>
<div id="footer">
    <div class="container">
        <div class="fbox1">
            <span class="icon icon-map-marker"></span>
            <span>THEJOEUN ACADEMY Corp.
			<br/>Sinchon Campus, 708</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-phone"></span>
            <span>
				Telephone: +1 800 123 4657
			</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-envelope"></span>
            <span>businessname@business.com</span>
        </div>
    </div>
</div>
<div id="copyright">
    <p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by <a
            href="http://templated.co" rel="nofollow">TEMPLATED</a>.<br>
        4조(박현정, 양준호, 유승종) - django project.</p>
</div>

</body>
</html>

templates/base2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>

    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Quicksand:400,700|Questrial"
          rel="stylesheet"/>
    <link href="{% static 'default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#logout").click(function () {
                $.ajax({
                    url: "{% url 'member_logout' %}",
                    success: function () {
                        alert("로그아웃!")
                        location.href = "{% url 'i_list' %}"  //이거말고 메인으로
                    }
                })
            }) // 로그아웃

            $("#reserve").click(function () {
                id = '{{ request.session.id }}'
                if (id == "") {
                    alert('로그인이 필요한 서비스입니다.')
                    location.href = "{% url 'login' %}"
                } else {
                    location.href = "{% url 'reserve:book' %}"
                }
            })
            $("#member_info").click(function () {
                id = '{{ request.session.id }}'
                if (id == "") {
                    alert('로그인이 필요한 서비스입니다.')
                    location.href = "{% url 'login' %}"
                } else {
                    location.href = "{% url 'login_info' %}"
                }
            })
        })
    </script>
    {% block script %}{% endblock %}
    {% block style %}{% endblock %}
</head>
<body>
<div id="header-wrapper">
    <br>
    {% if request.session.id == "" %}
        <div style="text-align: right;margin-right: 20px">
            <a href="{% url 'login' %}" style="color: white;"><b>로그인</b></a>&nbsp&nbsp&nbsp<font style="color: dimgray">|</font>&nbsp&nbsp&nbsp<a
                href="{% url 'create' %}" style="color: white"><b>회원가입</b></a>
        </div>
    {% else %}
        <div style="text-align: right;margin-right: 60px">
        <font style="color: white">{{ request.session.id }}님 환영합니다.&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp</font>
            <a href="#" id="logout" style="color: white;"><b>로그아웃</b></a>
        </div>
    {% endif %}

    <div id="header" class="container">
        <div>
            <h1><a style="color: white; text-decoration: none;" href="{% url 'i_list' %}">Big MegaBox</a></h1>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'i_list' %}">&nbsp&nbsp&nbsp영 화&nbsp&nbsp&nbsp</a></li>
                <li class="active"><a id="reserve" href="#">&nbsp&nbsp&nbsp예 매&nbsp&nbsp&nbsp</a></li>
                <li><a id="member_info" href="#">회원 정보</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="wrapper">
    <div id="welcome" class="container">
        {% block content %}{% endblock %}
    </div>
</div>
<div id="footer">
    <div class="container">
        <div class="fbox1">
            <span class="icon icon-map-marker"></span>
            <span>THEJOEUN ACADEMY Corp.
			<br/>Sinchon Campus, 708</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-phone"></span>
            <span>
				Telephone: +1 800 123 4657
			</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-envelope"></span>
            <span>businessname@business.com</span>
        </div>
    </div>
</div>
<div id="copyright">
    <p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by <a
            href="http://templated.co" rel="nofollow">TEMPLATED</a>.<br>
        4조(박현정, 양준호, 유승종) - django project.</p>
</div>

</body>
</html>

templates/base3.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>

    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Quicksand:400,700|Questrial"
          rel="stylesheet"/>
    <link href="{% static 'default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#logout").click(function () {
                $.ajax({
                    url: "{% url 'member_logout' %}",
                    success: function () {
                        alert("로그아웃!")
                        location.href = "{% url 'i_list' %}"  //이거말고 메인으로
                    }
                })
            }) // 로그아웃

            $("#reserve").click(function () {
                id = '{{ request.session.id }}'
                if (id == "") {
                    alert('로그인이 필요한 서비스입니다.')
                    location.href = "{% url 'login' %}"
                } else {
                    location.href = "{% url 'reserve:book' %}"
                }
            })

            $("#member_info").click(function () {
                id = '{{ request.session.id }}'
                if (id == "") {
                    alert('로그인이 필요한 서비스입니다.')
                    location.href = "{% url 'login' %}"
                } else {
                    location.href = "{% url 'login_info' %}"
                }
            })
        })
    </script>
    {% block script %}{% endblock %}
    {% block style %}{% endblock %}
</head>
<body>
<div id="header-wrapper">
    <br>
    {% if request.session.id == "" %}
        <div style="text-align: right;margin-right: 20px">
            <a href="{% url 'login' %}" style="color: white;"><b>로그인</b></a>&nbsp&nbsp&nbsp<font style="color: dimgray">|</font>&nbsp&nbsp&nbsp<a
                href="{% url 'create' %}" style="color: white"><b>회원가입</b></a>
        </div>
    {% else %}
        <div style="text-align: right;margin-right: 60px">
        <font style="color: white">{{ request.session.id }}님 환영합니다.&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp</font>
            <a href="#" id="logout" style="color: white;"><b>로그아웃</b></a>
        </div>
    {% endif %}

    <div id="header" class="container">
        <div>
            <h1><a style="color: white; text-decoration: none;" href="{% url 'i_list' %}">Big MegaBox</a></h1>
        </div>
        <div id="menu">
            <ul>
                <li><a href="{% url 'i_list' %}">&nbsp&nbsp&nbsp영 화&nbsp&nbsp&nbsp</a></li>
                <li><a id="reserve" href="#">&nbsp&nbsp&nbsp예 매&nbsp&nbsp&nbsp</a></li>
                <li class="active"><a id="member_info" href="#">회원 정보</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="wrapper">
    <div id="welcome" class="container">
        {% block content %}{% endblock %}
    </div>
</div>
<div id="footer">
    <div class="container">
        <div class="fbox1">
            <span class="icon icon-map-marker"></span>
            <span>THEJOEUN ACADEMY Corp.
			<br/>Sinchon Campus, 708</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-phone"></span>
            <span>
				Telephone: +1 800 123 4657
			</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-envelope"></span>
            <span>businessname@business.com</span>
        </div>
    </div>
</div>
<div id="copyright">
    <p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by <a
            href="http://templated.co" rel="nofollow">TEMPLATED</a>.<br>
        4조(박현정, 양준호, 유승종) - django project.</p>
</div>

</body>
</html>

templates/base_backup2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>

    <title>{% block title %}{% endblock %}</title>

    {% load static %}
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Quicksand:400,700|Questrial"
          rel="stylesheet"/>
    <link href="{% static 'default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>

    {% block script %}{% endblock %}
    {% block style %}{% endblock %}
</head>
<body>
<div id="header-wrapper">
    <div id="header" class="container">
        <div id="logo">
            <span class="icon icon-cog"></span>
            <h1><a href="#">Big MegaBox</a></h1>
        </div>
        <div id="menu">
            <ul>
                <li class="active"><a href="#" accesskey="1" title="">MOVIE</a></li>
                <li><a href="#" accesskey="2" title="">RESERVE</a></li>
                <li><a href="#" accesskey="3" title="">THEATER</a></li>
                <li><a href="#" accesskey="4" title="">MEMBER</a></li>
{#                <li><a href="#" accesskey="5" title="">Contact Us</a></li>#}
            </ul>
        </div>
    </div>
</div>
<div class="wrapper">
    <div id="welcome" class="container">
        {% block content %}{% endblock %}
    </div>
</div>
<div id="footer">
    <div class="container">
        <div class="fbox1">
            <span class="icon icon-map-marker"></span>
            <span>THEJOEUN ACADEMY Corp.
			<br/>Sinchon Campus, 708</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-phone"></span>
            <span>
				Telephone: +1 800 123 4657
			</span>
        </div>
        <div class="fbox1">
            <span class="icon icon-envelope"></span>
            <span>businessname@business.com</span>
        </div>
    </div>
</div>
<div id="copyright">
    <p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by <a
            href="http://templated.co" rel="nofollow">TEMPLATED</a>.<br>
    4조(박현정, 양준호, 유승종) - django project.</p>
</div>
</body>
</html>