info/urls.py
from django.contrib import admin
from django.urls import path

from info import views
from info.views import InfoList
from info.views import ReplyList
import info.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', InfoList.as_view(), name='i_list'),
    path('infodetail/<movie_id>/', info.views.infodetail, name='i_detail'),
    path('replylist/<int:movie_id_id>', ReplyList.as_view(), name='r_list'),
    path('replycreate/<movie_id>/', info.views.replycreate, name='r_create'),
    path('replycreate2/<movie_id>/', info.views.replydbcreate, name='r_dbcreate'),
    path('replydelete/', info.views.replydelete, name='r_delete'),
    path('replyupdate/<reply_id>/<movie_id>/<content>/', info.views.replyupdate, name='r_update'),
    path('replyupdate2/<movie_id>/', info.views.replydbupdate, name='r_dbupdate'),
]

# from django.conf.urls.static import static
# from django.conf import settings
#
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movie/urls.py
from django.contrib import admin
from django.urls import path, include

import info.urls
import reserve.urls
import reserve.views
import member.urls
from info.views import InfoList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reserve/', include(reserve.urls)),
    path('member/',include(member.urls)),
    path('',include(info.urls)),
]

reserve/urls.py
from django.contrib import admin
from django.urls import path
from reserve.views import *

app_name = 'reserve'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book', Reservation_main.as_view(), name='book'),
    path('time/<int:movie_id>', select_time, name='time'),
    path('seat/<watchday>&<int:watchtime>&<int:theater>', select_seat, name='seat'),
    path('save', reserve_save, name='save'),
    path('fin/<insert_id>', reserve_fin, name='fin'),
    path('hadoop', hot, name='hot'),
]

reserve/models.py
from django.db import models
from member.models import Member


class Member2(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    pw = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    tel = models.CharField(max_length=100, null=True)
    add = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    birth = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, null=True)

    def __str__(self):
        return 'id: ' + self.id + ', pw: ' + self.pw


class Info(models.Model):
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    actor = models.CharField(max_length=100)
    runningtime = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    agecut = models.CharField(max_length=100)
    content = models.TextField()
    img = models.CharField(max_length=100)
    counting = models.IntegerField(null=True)

    def __str__(self):
        return '제목: ' + self.title + '감독: ' + self.director


class Reservation(models.Model):
    movie_id = models.ForeignKey(Info, on_delete=models.CASCADE)
    member_id = models.ForeignKey(Member, on_delete=models.CASCADE)
    watchday = models.CharField(max_length=100)
    watchtime = models.IntegerField()
    theater = models.IntegerField(default='')
    bookingday = models.DateTimeField()
    seat = models.CharField(max_length=100)
    person = models.IntegerField()


class Timetable(models.Model):
    theater = models.IntegerField()
    movie_id = models.ForeignKey(Info, on_delete=models.CASCADE)
    watchday = models.CharField(max_length=100)
    watchtime = models.IntegerField()

    def __str__(self):
        return str(self.theater) + '관' + self.watchday + str(self.watchtime) + '회차'


class Seat(models.Model):
    watchday = models.CharField(max_length=100)
    watchtime = models.IntegerField()
    theater = models.IntegerField()
    booking = models.CharField(max_length=100)

    def __str__(self):
        return str(self.theater) + ': ' + str(self.booking)

reserve/views.py
from django.http import HttpResponse
from django.shortcuts import render
import datetime
from django.views.generic import *
from reserve.hadoop import *
from reserve.models import *


# 예매 페이지 첫화면 -> 영화 전체 목록
class Reservation_main(ListView):
    model = Info
    template_name_suffix = '_reserve'


# 영화 선택시 timetable 테이블에서 해당 영화의 상영날짜, 회차 가져오기
def select_time(request, movie_id):
    list = Timetable.objects.filter(movie_id=movie_id)
    info = Info.objects.get(id=movie_id)
    title = info.title
    request.session['movie_id'] = movie_id  # 영화id 세션 설정
    return render(request, 'reserve/timetable.html', {'timetable': list, 'title': title})


# 상영관,날짜, 회차 선택시 seat 테이블에서 좌석 예매 현황 가져오기
def select_seat(request, watchday, watchtime, theater):
    # seat = Seat.objects.filter(watchday=watchday).filter(watchtime=watchtime).filter(theater=theater)
    seat = Seat.objects.filter(watchday=watchday, watchtime=watchtime, theater=theater)

    # 상영관,날짜, 회차 세션 설정
    request.session['theater'] = theater
    request.session['watchday'] = watchday
    request.session['watchtime'] = watchtime

    # booking 컬럼에 저장되어있는 문자열(000000000등) 쪼개서 인덱스와 함께 dict에 저장
    # (인덱스가 key, 예매 상태(0 or 1)가 value)
    # -> 템플릿에서 예매가능여부 띄우기 위함(0이면 예매 가능, 1이면 예매 불가능)
    seat_dic = dict()
    idx = 0
    for x in seat[0].booking:
        seat_dic[str(idx)] = x
        idx += 1
    return render(request, 'reserve/seat.html', {'seat': seat_dic})


# 좌석 선택 이후 Reservation에 행 추가
def reserve_save(request):
    # id, watchday, watchtime, theater, bookingday, seat, person, member_id_id, movie_id_id
    # id, bookingday는 자동생성, 아래 다섯개 컬럼은 세션
    watchday = request.session['watchday']
    watchtime = request.session['watchtime']
    theater = request.session['theater']
    member_id_id = request.session['id']
    movie_id_id = request.session['movie_id']

    # seat은 선택된 좌석번호(1번부터 시작), person은 관람인원
    # 넘겨받은 선택된 좌석id를 문자열로 변환하여 DB에 저장
    seat_list = request.POST.getlist('select_seat[]')
    seat = ''
    for i, x in enumerate(seat_list):
        seat += str(int(x) + 1)
        if i != len(seat_list) - 1:
            seat += ','  # list 마지막 값일 경우에만 콤마 생략
    person = len(seat_list)  # 관람인원(선택한 좌석의 개수)

    bookingday = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # reservation = Reservation(watchday=watchday, watchtime=watchtime, theater=theater, bookingday=bookingday, seat=seat, person=person, member_id_id=member_id_id, movie_id_id=movie_id_id)
    # result = reservation.save()
    result = Reservation.objects.create(watchday=watchday, watchtime=watchtime, theater=theater, bookingday=bookingday,
                                        seat=seat, person=person, member_id_id=member_id_id, movie_id_id=movie_id_id)
    seat_change(seat_list, watchday, watchtime, theater)
    make_txt(movie_id_id, person)
    return HttpResponse(result.id)


# Seat 테이블의 booking 컬럼 값 중 예매된 좌석의 상태 0 -> 1 변환
def seat_change(seat_list, watchday, watchtime, theater):
    before1 = Seat.objects.get(watchday=watchday, watchtime=watchtime, theater=theater)
    before = before1.booking  # 예매 진행 전 좌석예매현황

    # 문자열 업데이트 위해 list로 변환
    before_list = []
    for x in before:
        before_list.append(x)

    # 예매된 좌석에 해당하는 index의 값을 1로 변경
    for i in seat_list:
        before_list[int(i)] = '1'

    # 리스트를 다시 문자열로 변경
    after = ''
    for y in before_list:
        after += y

    # db 업데이트
    sid = before1.id  # 바꿔야하는 레코드의 pk
    Seat.objects.filter(id=sid).update(booking=after)


# 예매 완료시 예매한 영화의 id를 예매 인원수만큼 txt파일에 누적 -> 하둡 분석용
def make_txt(movie_id, person):
    bookingday = datetime.datetime.now().strftime("%Y-%m-%d")
    file = open('static/txt/' + str(bookingday) + '.txt', 'a', encoding='utf-8')
    i = 0
    while i < person:
        file.write(str(movie_id) + ' ')
        i += 1
    file.close()


# hadoop.py에서 top5 목록 가져와서 Info테이블의 title과 매칭
def hot(request):
    top5_list = top5()
    title_list = ''
    for i, one in enumerate(top5_list):
        title = Info.objects.get(id=one['movie_id']).title
        title_list += (str(i + 1) + '위: ' + title)
        if i != len(top5_list) - 1:
            title_list += '<br>'
    return HttpResponse(title_list)


# 예매한 내역의 상세 정보 select
def reserve_fin(request, insert_id):
    # pk int 변환
    insert_id2 = int(insert_id)
    # 예매 완료된 레코드 정보
    reserve_info = Reservation.objects.filter(id=insert_id2)

    # FK(movie_id) 이용하여 Info 테이블에서 예매한 영화 title get
    title = Reservation.objects.select_related('movie_id').get(id=insert_id2).movie_id.title

    # 세션끊기: watchday, watchtime, theater, movie_id
    del request.session['watchday']
    del request.session['watchtime']
    del request.session['theater']
    del request.session['movie_id']

    # 예매 내역과 영화제목 넘김
    return render(request, 'reserve/reserve_fin.html', {'reserve_info': reserve_info, 'title': title})

reserve/templates/reserve/info_reserve.html
{% extends 'base2.html' %}

{% block title %}빠른 예매{% endblock %}
{% block style %}
    <style>
        #top5 {
            font-size: 20px;
            line-height: 30px;
        }

        #list {
            overflow: scroll;
            font-size: 20px;
            line-height: 40px;
            margin: 0 auto;
            padding: 10px 0px;
            width: 400px;
            height: 300px;
            background-color: #daf8ff;
        }

        a {
            line-height: 30px;
            color: midnightblue;
            text-decoration: none;
        }

        a:hover {
            font-weight: bold;
        }

        .movie_li:nth-child(even) {
            background-color: #eeeeee;
        }
    </style>
{% endblock %}
{% block script %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $.ajax({
                url: "{% url 'reserve:hot' %}",
                success: function (result) {
                    $("#top5").append(result)
                }
            })
        })
    </script>
{% endblock %}
{% block content %}
    <h1>무비차트 TOP5</h1>
    <br>
    <div id="top5"></div>
    <br>
    <hr width="40%" color="red">
    <br>
    <h1>영화 선택</h1>
    <br>
    <div id="list">
        <ul>
            {% for movie in object_list %}
                <li class="movie_li"><a href="{% url 'reserve:time' movie_id=movie.id %}">{{ movie.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

reserve/templates/reserve/reserve_fin.html
{% extends 'base2.html' %}

{% block title %}예매 확인{% endblock %}
{% block style %}
    <style>
        #go_main {
            background-color: #2056ac;
            color: white;
            width: 200px;
            height: 50px;
            font-size: 20px;
            border: none;
        }

        #detail_info {
            width: 500px;
            margin: 0 auto;
            font-size: 20px;
            {% comment %}border-collapse: collapse;{% endcomment %}
            border: 1px solid navy;
        }

        .row1 {
            height: 50px;
        }
    </style>
{% endblock %}
{% block content %}
    <h1>예매 내역</h1>
    <hr width="60%" color="red">
    <br>
    <h2>< {{ title }} ></h2>
    <br>
    <table id="detail_info">
        <tr class="row1">
            <td width="30%">관람일</td>
            <td width="70%">{{ reserve_info.0.watchday }}</td>
        </tr>
        <tr class="row1">
            <td>관람 회차</td>
            <td>{{ reserve_info.0.watchtime }}회차
                {% if reserve_info.0.watchtime == 1 %}
                    (시작시간 07:00)
                {% elif reserve_info.0.watchtime == 2 %}
                    (시작시간 10:00)
                {% elif reserve_info.0.watchtime == 3 %}
                    (시작시간 13:00)
                {% elif reserve_info.0.watchtime == 4 %}
                    (시작시간 16:00)
                {% elif reserve_info.0.watchtime == 5 %}
                    (시작시간 19:00)
                {% else %}
                    (시작시간 22:00)
                {% endif %}
            </td>
        </tr>
        <tr class="row1">
            <td>상영관</td>
            <td>{{ reserve_info.0.theater }}관</td>
        </tr>
        <tr class="row1">
            <td>관람인원</td>
            <td>{{ reserve_info.0.person }}명</td>
        </tr>
        <tr class="row1">
            <td>좌석번호</td>
            <td>{{ reserve_info.0.seat }}</td>
        </tr>
        <tr class="row1">
            <td>예매시간</td>
            <td>{{ reserve_info.0.bookingday | date:'Y-m-d H:i' }}</td>
        </tr>
    </table>
    <br>
    <button id="go_main" onclick="location.href='{% url "i_list" %}'">메인페이지로</button>
{% endblock %}

reserve/templates/reserve/seat.html
{% extends 'base2.html' %}

{% block title %}좌석 선택{% endblock %}
{% block style %}
    <style>
        .con {
            width: 25px;
        }

        .con_text {
            text-align: left;
            font-size: 20px;
            font-weight: bold;
            color: black;
            padding-left: 10px;
            padding-right: 30px;
        }

        #next {
            margin: 70px auto;
            padding: 10px;
            width: 200px;
            background-color: #48ecea;
            color: navy;
            font-size: 20px;
            font-weight: bold;
            border: 1px solid navy;
        }

        .seat_btn {
            background-color: blue;
            width: 60px;
            height: 60px;
            color: white;
            font-size: 20px;
            font-weight: bold;
        }

        #screen {
            margin: 0 auto;
            padding: 10px 0;
            display: block;
            width: 700px;
            background-color: midnightblue;
            color: whitesmoke;
            font-size: 30px;
        }
    </style>
{% endblock %}
{% block script %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $(".seat_btn").click(function () {
                // 좌석 버튼 클릭시 빨간색으로 버튼 색 변경
                color = $(this).css('background-color')
                if (color == 'rgb(0, 0, 255)') {
                    $(this).css('background-color', 'red')
                    $(this).addClass('red')
                } else { // 빨간색 좌석 선택시 선택 취소 -> 다시 파란색으로
                    $(this).css('background-color', 'blue')
                    $(this).removeClass('red')
                }
            }) // 좌석 버튼 클릭

            $("#next").click(function () {
                count = $("button").length - 1 // 좌석 버튼의 개수
                select_seat = [] // 선택된 좌석의 id 담아놓을 배열
                for (i = 0; i < count; i++) {
                    btn = $("#" + i)
                    id = $("#" + i).attr('id')
                    if (btn.hasClass('red')) { // 선택된(빨간색) 좌석의 id를 배열에 push
                        select_seat.push(id)
                    }
                } // for
                if (select_seat.length == 0) {
                    alert("좌석을 선택해 주세요.")
                } else {
                    alert(select_seat.length + "개의 좌석을 선택하셨습니다.")
                    $.ajax({
                        type: 'POST',
                        url: "{% url 'reserve:save' %}",
                        data: {
                            'select_seat[]': select_seat,
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                        },
                        success: function (result) {
                            if (result != null) {
                                location.href = "{% url 'reserve:fin' insert_id='result' %}".replace('result', result)
                            }
                        }
                    }) // ajax
                }
            }) // 좌석 선택 완료 버튼 클릭
        }) // main
    </script>
{% endblock %}
{% block content %}
    <table style="margin: 0 auto">
        <tr>
            <td class="con" style="background-color: red;"></td>
            <td class="con_text">: 선택된 좌석</td>
            <td class="con" style="background-color: blue;"></td>
            <td class="con_text">: 예매 가능</td>
            <td class="con" style="background-color: gray;"></td>
            <td class="con_text">: 예매 불가</td>
        </tr>
    </table>
    <br><br>
    <label id="screen">SCREEN</label>
    <br><br>
    {% for key, value in seat.items %}
        {% if value == '0' %}
            <button class="seat_btn" id="{{ key }}">{{ forloop.counter }}</button>
        {% else %}
            <button style="background-color: gray;" class="seat_btn" id="{{ key }}"
                    disabled="disabled">{{ forloop.counter }}</button>
        {% endif %}
    {% endfor %}
    <br>
    <button id="next">좌석 선택 완료</button>
{% endblock %}

reserve/templates/reserve/timetable.html
{% extends 'base2.html' %}

{% block title %}날짜/회차 선택{% endblock %}
{% block style %}
    <style>
        td {
            border: 1px solid navy;
        }

        span {
            color: midnightblue;
            line-height: 50px;
            font-size: 30px;
        }

        a {
            text-decoration: none;
        }

        a:hover {
            font-weight: bold;
        }
    </style>
{% endblock %}
{% block content %}
    <h1>상영시간표</h1>
    <table style="width: 500px; margin: 20px auto; border-collapse: collapse; font-size: 20px;">
        <tr>
            <td>회차</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
        </tr>
        <tr>
            <td>시작시간</td>
            <td>07:00</td>
            <td>10:00</td>
            <td>13:00</td>
            <td>16:00</td>
            <td>19:00</td>
            <td>22:00</td>
        </tr>
    </table>
    <br>
    <hr width="60%" color="red">
    <br>
    <h2>{{ title }} - 관람일/회차 선택</h2>
    <br>
    <hr width="30%">
    <br>
    {% for time in timetable %}
        <span>[ <a
                href="{% url 'reserve:seat' watchday=time.watchday watchtime=time.watchtime theater=time.theater %}">
            {{ time.theater }}관
            {{ time.watchday }}
            {{ time.watchtime }}회차</a> ]</span><br>
    {% endfor %}
{% endblock %}